spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdata
    username: root
    password: welcome1
  jpa:
    generate-ddl: false
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    user:
      name: user
      password: welcome1