server:
  port: 8080
spring:
  application:
    name: distributor-network
  profiles:
    active:
      - test
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - refresh